-- AlterTable
ALTER TABLE "Account" ALTER COLUMN "accountId" DROP DEFAULT,
ALTER COLUMN "providerId" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;

-- AlterTable
ALTER TABLE "Session" ALTER COLUMN "token" DROP DEFAULT,
ALTER COLUMN "expiresAt" DROP DEFAULT,
ALTER COLUMN "updatedAt" DROP DEFAULT;
